from enum import Enum

from pydantic import BaseModel, Field


class ConfidenceScoreEnum(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"


class RAGResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The answer generated by the RAG model Based on the retrieved documents.",
    )
    sources: list[str] = Field(
        ..., description="The names of the PDFs supporting the answer."
    )
    page_numbers: list[int] | None = Field(
        None, description="The page numbers of the PDFs supporting the answer."
    )
    confidence_score: ConfidenceScoreEnum | None = Field(
        None,
        description="The confidence score of the answer generated by the RAG model.",
    )
