from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum

class ConfidenceScoreEnum(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"
class RAGResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the RAG model Based on the retrieved documents.")
    sources: List[str] = Field(..., description="The names of the PDFs supporting the answer.")
    page_numbers: Optional[List[int]] = Field(None, description="The page numbers of the PDFs supporting the answer.")
    confidence_score: Optional[ConfidenceScoreEnum] = Field(None, description="The confidence score of the answer generated by the RAG model.")
